Add snackbars
uwblueprint/paramedics-react pull request #25
Opened 2020-08-12 00:03 UTC by wongcmichelle

## Overview
>[Code review doc for reference](https://www.notion.so/uwblueprintexecs/Code-Review-a21fc85b00394f488e92d9d605f6b2bc)

[Notion task](https://www.notion.so/uwblueprintexecs/on-entity-create-event-snackbar-4b64273fa7aa423d8504aada96547f28)

## Changes
- Add snackbars for the following
    - Users (or team members) add/edit/delete
    - Hospitals add/edit/delete
    - Ambulances add/edit/delete

## Testing
A snackbar should appear for each of these cases:
- Go to '/manage/members'
    - Add a team member
    - Edit a team member
    - Delete a team member

- Go to '/manage/hospitals'
    - Add a hospital
    - Edit a hospital
    - Delete a hospital

- Go to '/manage/ambulances'
    - Add an ambulance
    - Edit an ambulance
    - Delete an ambulance

## Screenshots
Resource management:
![image](https://user-images.githubusercontent.com/22457859/89960673-a807f200-dc0d-11ea-8d58-9403e331713b.png)

2020-08-12 22:11 UTC, petorsong requested changes
looks good except for 1 typo - would be good to double check with designers about the UX (e.g. if you spam 2 mutations quickly, you get 2 snackbars on the screen at the same time; also timeout intervals and other styling)

2020-08-12 22:11 UTC, petorsong commented on src/components/ResourceForm/AmbulanceFormPage.tsx
> +      enqueueSnackbar('Ambulance deleted.');
```suggestion
      enqueueSnackbar('Ambulance added.');
```

2020-08-16 10:06 UTC, petorsong approved these changes

2020-08-17 00:44 UTC, rickrm commented
@wongcmichelle LGTM!

2020-08-17 00:44 UTC, rickymao approved these changes

2020-08-17 00:58 UTC, merged