Fixed inconsistent dates for different event pages
uwblueprint/paramedics-react pull request #49
Opened 2020-11-04 04:56 UTC by sarafong

[Notion ticket](https://www.notion.so/uwblueprintexecs/Edit-Event-Page-Event-calendar-display-s-today-s-date-not-the-event-date-86c88f5c2a40478a830f66628bb1fedb)

## Changes
- Because we only collect month/day, time zone gets messed up since it is at UTC 00:00. Changed to parse month/date at UTC time
- Fixed off by one error for month label array

## Screenshots

## Testing
- Verify event dates are the same on home page, event page, and edit event page

## Checklist
>[Code review doc for reference](https://www.notion.so/uwblueprintexecs/Code-Review-a21fc85b00394f488e92d9d605f6b2bc)

before opening PR
- [x] check notion ticket
- [x] run linter
- [x] go through file diff

filling out PR
- [x] descriptive title
- [x] update `notion ticket` link
- [ ] update `figma link`
- [x] fill out `Changes`
  - [ ] \(optional) add inline comments in diff
- [ ] fill out `Testing`
- [ ] \(optional) add `Screenshots`
- [x] assign yourself to the PR

after opening PR
- [ ] link PR to notion ticket
- [ ] move ticket to `In PR`
- [ ] make sure build passes
- [ ] ping `@ps` in `#paramedics-dev`

2020-11-04 05:00 UTC, sarafong commented
After I made the PR I found a bug with my fix when you create a new event so please hold off on reviewing :(

2020-11-08 02:56 UTC, sarafong commented
ok it's good to go now! @petorsong @patrick-du

2020-11-08 04:04 UTC, petorsong requested changes
this date business is kind of confusing me and i'm not sure how we want to approach this from a UX perspective - let's pull rishabh in and chat next work session

* i tested this at about 8 pm PST and i got a mismatch between my selected date and the displayed date
![image](https://user-images.githubusercontent.com/59516223/98456519-957d5600-2133-11eb-983f-e75a415e6358.png)
* also the `moment` library will no longer be maintained as of sep 2020, so i would prefer to not introduce it into any new code - this has some suggestions for how to approach that
  * https://momentjs.com/docs/#/-project-status/

2020-11-11 03:20 UTC, sarafong commented
yikes ok looks like it's still mismatched, need to test this further. also very unfortunate that moment is being discontinued :(

2020-11-21 22:00 UTC, sarafong commented
ready to be reviewed again!

2020-11-22 02:37 UTC, petorsong approved these changes
seems to be working now whoo

2020-11-22 02:37 UTC, petorsong commented on src/components/EventCreation/EventCreationPage.tsx
> +        day: eventDate.split('-')[2],
do we need to add the `literal` field as well?

2020-11-22 18:15 UTC, patrick-du commented
Nice work! 

Not sure why but I'm getting a mismatch in the `Edit Event` page between the date that's in the input field and the date displayed in the date picker. 

Besides this, the rest of the PR looks good and the dates are consistent between the other screens.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/41495076/99911746-700c5280-2cc4-11eb-9428-9be778514860.gif)

2020-11-25 00:07 UTC, patrick-du approved these changes

2020-11-25 00:11 UTC, merged