Route into CCP from CCP Table
uwblueprint/paramedics-react pull request #52
Opened 2020-11-06 02:51 UTC by patrick-du

[Notion ticket](https://www.notion.so/uwblueprintexecs/Route-into-CCP-from-CCP-Table-efaed55c7635495c92d989d9148aea17)

## Changes
- Added click handler for CCP table rows to route to respective CCP dashboard

## Testing
- Click on any CCP table row and it should route you to the dashboard
- For example: clicking on the Checkpoint 0 row routes to the Checkpoint 0 dashboard
![image](https://user-images.githubusercontent.com/41495076/98320343-b9fcf500-1fb0-11eb-816c-fdb3361b72e3.png)
![image](https://user-images.githubusercontent.com/41495076/98320348-bd907c00-1fb0-11eb-8cb1-585860eadb35.png)

## Checklist
>[Code review doc for reference](https://www.notion.so/uwblueprintexecs/Code-Review-a21fc85b00394f488e92d9d605f6b2bc)

before opening PR
- [x] check notion ticket
- [x] run linter
- [x] go through file diff

filling out PR
- [x] descriptive title
- [x] update `notion ticket` link
- [ ] update `figma link`
- [x] fill out `Changes`
  - [ ] \(optional) add inline comments in diff
- [x] fill out `Testing`
- [ ] \(optional) add `Screenshots`
- [x] assign yourself to the PR

after opening PR
- [ ] link PR to notion ticket
- [ ] move ticket to `In PR`
- [ ] make sure build passes
- [ ] ping `@ps` in `#paramedics-dev`

2020-11-07 19:45 UTC, petorsong approved these changes
🏃‍♀️

2020-11-07 21:34 UTC, petorsong requested changes
clicking the triple dot menu on the right also takes you into the CCP page - i believe some `e.preventDefault()` business needs to be done to retain that functionality

2020-11-09 06:11 UTC, petorsong approved these changes
`e.preventDefault` was along the same lines of `e.stopPropagation` so i'm just gonna pretend i was helpful 💡

2020-11-20 01:32 UTC, sarafong approved these changes

2020-11-20 01:56 UTC, merged